services:

    agit.ui.page:
        class: Agit\UiBundle\Service\PageService
        arguments: [@agit.ui.page.loader, @agit.core.url, @agit.intl.locale, @?agit.user]

    agit.ui.page.loader:
        private: true
        class: CacheLoader
        factory_service:  agit.plugin.cache.loader.factory
        factory_method:   create
        arguments: [ agit.ui.page ]

    # registration listener
    agit.ui.page.register:
        private: true
        class: CacheAwareServiceListener
        factory_service:  agit.pluggable.cache.listener.factory
        factory_method:   create
        arguments: [ agit.ui.page ]
        tags: [{ name: kernel.event_listener, event: agit.pluggable, method: onRegistration }]

    agit.ui.page.listener.factory:
        arguments: [ @agit.core.filecollector, @twig ]
        class: Agit\UiBundle\EventListener\UiPageListenerFactory


    agit.ui.page.plugins:
        private: true
        class: UiPageListener
        factory_service:  agit.ui.page.listener.factory
        factory_method:   create
        arguments: [ AgitUiBundle:Resources:views, 10 ]
        tags: [{ name: kernel.event_listener, event: agit.ui.page, method: onRegistration }]


    # Handles our custom Twig syntax for the page meta data
    agit.ui.custom:
        class: Agit\UiBundle\TwigMeta\PageConfigTokenExtension
        tags:
            - { name: twig.extension }
        arguments:  []

    # misc template functions
    agit.ui.pagecontent:
        class: Agit\UiBundle\Twig\PageContentExtension
        tags:
            - { name: twig.extension }
        arguments:  [@agit.ui.page, @agit.intl.locale, @?agit.localedata.locale]

    # simple form builder for API objects
    agit.ui.formbuilder:
        class: Agit\UiBundle\Twig\ApiFormBuilderExtension
        tags:
            - { name: twig.extension }
        arguments:  [@twig, @agit.api.object]


    #
    # listeners for the intl catalog service
    #

    # checks if a bundle has Twig templates, and prepares them for extraction
    agit.ui.intl.twig:
        class: Agit\UiBundle\EventListener\IntlCatalogTwigFilesListener
        arguments: [ @agit.core.filecollector, @twig ]
        tags: [{ name: kernel.event_listener, event: agit.intl.files.register, method: onRegistration }]

    # cleans up temporary files
    agit.ui.intl.twig.cleanup:
        parent: agit.intl.listener.files.cleanup
        tags: [{ name: kernel.event_listener, event: agit.intl.files.cleanup, method: onRegistration }]
