services:

    agit.ui.page:
        class: Agit\UiBundle\Service\PageService
        arguments: [@agit.ui.page.loader, @agit.user, @agit.core.url, @?agit.ui.lang.provider]

    agit.ui.page.loader:
        private: true
        class: CacheLoader
        factory_service:  agit.plugin.cache.loader.factory
        factory_method:   create
        arguments: [ agit.ui.page ]

    # registration listener
    agit.ui.page.register:
        private: true
        class: CacheAwareServiceListener
        factory_service:  agit.pluggable.cache.listener.factory
        factory_method:   create
        arguments: [ agit.ui.page ]
        tags: [{ name: kernel.event_listener, event: agit.pluggable, method: onRegistration }]

    agit.ui.page.listener.factory:
        arguments: [ @agit.core.filecollector, @twig ]
        class: Agit\UiBundle\EventListener\UiPageListenerFactory


    agit.ui.page.plugins:
        private: true
        class: UiPageListener
        factory_service:  agit.ui.page.listener.factory
        factory_method:   create
        arguments: [ AgitUiBundle:Resources:views, 10 ]
        tags: [{ name: kernel.event_listener, event: agit.ui.page, method: onRegistration }]


    # Handles our custom Twig syntax for the page meta data
    agit.ui.custom:
        class: Agit\UiBundle\Twig\PageConfigTokenExtension
        tags:
            - { name: twig.extension }
        arguments:  []
