services:

    agit.ui.page:
        class: Agit\UiBundle\Service\PageService
        arguments: [ @agit.pluggable.cache.loader_factory, @agit.common.url, @agit.intl.locale, @?agit.user ]
        tags: [{ name: agit.pluggable, type: cache, tag: agit.ui.pages, baseClass: Agit\UiBundle\Plugin\UiPagePlugin }]

    # Handles our custom Twig syntax for the page meta data
    agit.ui.custom:
        class: Agit\UiBundle\TwigMeta\PageConfigTokenExtension
        tags:
            - { name: twig.extension }

    # misc template functions
    agit.ui.pagecontent:
        class: Agit\UiBundle\Twig\PageContentExtension
        tags:
            - { name: twig.extension }
        arguments:  [ @agit.ui.page, @agit.intl.locale, @?agit.localedata.language ]

    # page navigation functions
    agit.ui.pagenavigation:
        class: Agit\UiBundle\Twig\PageNavigationExtension
        tags:
            - { name: twig.extension }
        arguments:  [@agit.ui.page]
